remote_theme: "mmistakes/minimal-mistakes@4.22.0"

plugins:
  - jekyll-include-cache

locale: "en-GB"

title: "Dave Cross"
subtitle: "I'm Dave and this is my web site"
name: "Dave Cross"
timezone: Europe/London

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XYYWCL6B9R"
