remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

locale: "en-GB"

title: "Dave Cross"
subtitle: "I'm Dave and this is my web site"
name: "Dave Cross"
timezone: Europe/London
locale: "en-GB"
repository: "davorg/dave.org.uk"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XYYWCL6B9R"

atom_feed:
  hide: true
