remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

locale: "en-GB"

title: "Dave Cross"
subtitle: "I'm Dave and this is my web site"
name: "Dave Cross"
timezone: Europe/London
locale: "en-GB"
repository: "davorg/dave.org.uk"

author:
  name: Dave Cross
  home: https://davecross.co.uk/
  avatar: /assets/images/dave-avatar.png

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XYYWCL6B9R"

atom_feed:
  hide: true

after_footer_scripts:
  - /assets/js/ga4-404.js

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/davorg"
    - label: "Other links"
      url: "https://links.davecross.co.uk/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      header:
        image: /assets/images/header_ducks_trim.jpg
